### ISSUE TITLE
Minification problem when using @inherits ...<> 

### ISSUE THREAD

**Issue by 06b** [deanhume/html-minifier#13]
Since I'm using Nancy with Razor, I have to add <code>@inherits Nancy.ViewEngines.Razor.NancyRazorViewBase<dynamic></code> to the top of each view in order to enable intellisense (it appears to work without being on the top of each view, but I believe this is common to those who use Nancy with Razor to place it at the top)

Similar to issue #10 I believe it's due to the fact it ends with >

As a temporary workaround I've moved the <code>@Inherits</code> section to the very bottom of the view.

**Comment by deanhume** [comment]
Would it be possible for you to post a sample of your view and I'll update the tests....

**Comment by 06b** [comment]
Sure, below's a generic error view


```
@inherits Nancy.ViewEngines.Razor.NancyRazorViewBase<dynamic>
@{
    Layout = "Views/Shared/_Layout.cshtml";
}

<h1>Looks like something went wrong.</h1>

<p>Sorry, we are experiencing technical difficulties. We are working on getting this problem resolved. Sorry for any inconvenience!</p>
```

**Comment by deanhume** [comment]
Hi @06b - this has been fixed in the latest release. Let me know how it goes for you!

https://github.com/deanhume/html-minifier/releases/tag/v1.4

**Comment by 06b** [comment]
Hey @deanhume - I haven't had a chance to fully look into this however it looks like I'm still having some issues (however it could be due to something else I'm doing with the project I'm currently using the html minifier on - I'll try creating a new project sometime this week to confirm that this issue is fixed)

I noticed when I was quickly looking over the commit for the fix that the GithubIssue13Result.txt file seems to be missing from the HtmlMinifier.Tests/Data folder, just as an fyi.

**Comment by 06b** [comment]
Hey @deanhume - So did some testing, the Minifier does in fact work however it appears the issue is that when @inherits is being used - it errors out if another @ ends up following it on the same line.

So if I did @inherits followed by @{ Layout = ""} or @using - it will cause the it to not render - The work around I could foresee would be if @inherits is used  after the > to perhaps do a new line.
